//
// BSODomizer HD
//
// Filename: 	IR_Decoder.h
// Author: 	  Joe Grand [www.grandideastudio.com] and Zoz
//
// Description: IR (NEC/Apple Remote) Decoder header file
//
// Distributed under a Creative Commons Attribution 3.0 United States license
// http://creativecommons.org/licenses/by/3.0/us/ 
//

/*****************************************************************************/
/* DRIVER CONFIGURATION                                                      */
/* ====================                                                      */
/*                                                                           */
/* The following defines need to be defined by the user.                     */
/*                                                                           */
/* The following configuration items are mandatory:                          */
/* - NEC_DATA_PIN:      NEC input pin                                        */
/* - NEC_TICKS_PER_MS:  NEC timer ticks per millisecond                      */
/* - NEC_GetTimer():    Macro to get NEC timer value                         */
/*                                                                           */
/*****************************************************************************/

// Apple remote receiver sensor connection
#define NEC_DATA_PIN        RA2
#define NEC_DECODER_TRISx   TRISA2
#define NEC_DECODER_ANSx    ANSA2
#define NEC_DECODER_WPUx    WPUA2
#define NEC_DECODER_IOCxP   IOCAP2
#define NEC_DECODER_IOCxN   IOCAN2
#define NEC_DECODER_IOCxF   IOCAF2

// Timer 0 is configured to increment every 128.0us (i.e. 1000/128 times per ms)
#define NEC_TICKS_PER_MS (1000/128)

// Timer 0 used for time measurement of RC5 signal
#define NEC_GetTimer() TMR0

// States of the system
#define STATE_WAIT_PREPULSE	0x00
#define STATE_WAIT_SPACE	0x01
#define STATE_READING_DATA	0x02

/**************************************************************************
************************** Typedefs ***************************************
***************************************************************************/

typedef enum	// 7-bit command 
{
  APPLE_UP = 0x05,
  APPLE_DOWN = 0x06,
  APPLE_LEFT = 0x04,
  APPLE_RIGHT = 0x03,
  APPLE_CENTER = 0x02,
  APPLE_MENU = 0x01,
} apple_cmd_type;


/*--- Apple remote data structure ---*/

typedef struct {
    apple_cmd_type command;
    uint8_t valid;
} APPLE_DECODE;

extern volatile APPLE_DECODE Apple_Decode;

/* pin where NEC signal is connected needs to be configured in NED_DATA_PIN */
#ifndef NEC_DATA_PIN
#error NEC_DATA_PIN not defined!
#endif

/* number of ticks per ms which are generated by the timer which is used */
/* for NEC decoding, needs to be defined in NEC_TICKS_PER_MS */
#ifndef NEC_TICKS_PER_MS
#error NEC_TICKS_PER_MS not defined!
#endif

/* function to get current timer value needs to be configured in NEC_GetTimer() */
#ifndef NEC_GetTimer()
#error NEC_GetTimer() not defined!
#endif


/*****************************************************************************/
/* DRIVER INTERNAL DEFINES                                                   */
/* =======================                                                   */
/*                                                                           */
/* Do not change any of thess defines.                                       */
/*****************************************************************************/

#define NEC_GetPin()            input(NEC_DATA_PIN)

// timeout time after last NEC interrupt
#define NEC_PREPULSE             ((NEC_TICKS_PER_MS) * 8)
#define NEC_SPACE               ((NEC_TICKS_PER_MS) * 4)
#define NEC_TIMEOUT             ((NEC_TICKS_PER_MS) * 11)
#define NEC_BIT                 ((NEC_TICKS_PER_MS))


/*****************************************************************************/
/* NEC_DECODER_GetCmd                                                        */
/*                                                                           */
/* Extract the command (7 bits) from the full Apple Remote code              */
/*****************************************************************************/
static unsigned char lookup[16] = {0x0, 0x8, 0x4, 0xc, 0x2, 0xa, 0x6, 0xe, 0x1, 0x9, 0x5, 0xd, 0x3, 0xb, 0x7, 0xf};
#define NEC_MASK_CMD_LOWNIBBLE 0x00000F00
#define NEC_MASK_CMD_HIGHNIBBLE 0x00007000
#define NEC_DECODER_getCmd(neccode) ((lookup[(neccode & NEC_MASK_CMD_LOWNIBBLE)>>8] << 4) | (lookup[(neccode & NEC_MASK_CMD_HIGHNIBBLE)>>12]))


void NEC_DECODER_init(void);
uint8_t NEC_DECODER_codeReady(void);
uint16_t NEC_DECODER_getCode(void);
void NEC_DECODER_timeoutIncrement(void);
void NEC_DECODER_interruptHandler(void);
